# Settings in the [build] context are global and are applied to 
# all contexts unless otherwise overridden by more specific contexts.
[build]

# Production context: all deploys from the Production branch 
# set in your siteâ€™s Branches settings in the UI
# will inherit these settings.
[context.production]
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }
